export const GET_USER = "GET_USER";
export const AUTHENTICATED_LOGIN_ACCESS = "AUTHENTICATED_LOGIN_ACCESS";
export const AUTHENTICATED_LOGOUT_ACCESS = "AUTHENTICATED_LOGOUT_ACCESS";
export const UPDATE_USER = "UPDATE_USER";

export const UPDATE_SONG_STRING = "UPDATE_SONG_STRING"
export const UPDATE_TRACK_LIST = "UPDATE_TRACK_LIST"
export const UPDATE_SONG_PLAY = "UPDATE_SONG_PLAY"