export const AUTHENTICATED_LOGIN_ACCESS = "AUTHENTICATED_LOGIN_ACCESS";
export const AUTHENTICATED_LOGOUT_ACCESS = "AUTHENTICATED_LOGOUT_ACCESS";
export const INITIAL_LOGIN = "INITIAL_LOGIN"
export const USER_DATA = "USER_DATA";
export const SET_LOGOUT = "SET_LOGOUT"

export const SEND_BLOGGER_DATA = "SEND_BLOGGER_DATA"
export const ADMIN_AUTH = "ADMIN_AUTH"
export const SEND_MY_BLOGS = "SEND_MY_BLOGS"